opsdroid:
  image:
    repository: opsdroid/opsdroid
    tag: v0.28.0
    imagePullPolicy: IfNotPresent

  service:
    port: 8080

  resources:
    # limits:
    #   cpu: 1000m
    #   memory: 1Gi
    # requests:
    #   cpu: 100m
    #   memory: 1Gi

  pvc:
    enabled: false
    annotations: {}
    selector: {}
    accessModes:
      - ReadWriteOnce
    storage: 5Gi
    storageClassName:

  ingress:
    enabled: false
    # hosts:
    #   - opsdroid.example.com
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    # tls:
    #   - secretName: opsdroid-tls
    #     hosts:
    #       - opsdroid.example.com

  environment:
    #- name: "HTTP_PROXY"
    #  value: ""
    #- name: "HTTPS_PROXY"
    #  value: ""
    #- name: "http_proxy"
    #  value: ""
    #- name: "https_proxy"
    #  value: ""
    #- name: "no_proxy"
    #  value: ".cluster.local"

  configuration: |
    welcome-message: true
    skills:
      ## Dance (https://github.com/opsdroid/skill-dance)
      dance: {}

      ## Hello (https://github.com/opsdroid/skill-hello)
      hello: {}

      ## Loudnoises (https://github.com/opsdroid/skill-loudnoises)
      loudnoises: {}

      ## Seen (https://github.com/opsdroid/skill-seen)
      seen: {}
      # Configurations for other skills uncomment desired skill to activate it.
      devtools: {}

rasanlu:
  enabled: false

  token: abc123

  image:
    repository: rasa/rasa_nlu
    tag: 0.11.3-full
    imagePullPolicy: IfNotPresent

  service:
    port: 5000

  resources:
    # limits:
    #  cpu: 2000m
    #  memory: 8Gi
    # requests:
    #  cpu: 1000m
    #  memory: 4Gi

  pvc:
    enabled: false
    annotations: {}
    selector: {}
    accessModes:
      - ReadWriteOnce
    storage: 5Gi
    storageClassName:
