{{- if $.Values.opsdroid.configuration }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: opsdroid-{{ .Release.Name }}-config
data:
  configuration.yaml: |
{{ .Values.opsdroid.configuration | indent 4 }}
{{- end }}
