{{- if $.Values.opsdroid.environment }}
apiVersion: v1
kind: Secret
metadata:
  name: opsdroid-{{ .Release.Name }}-config
type: Opaque
data:
  {{- range .Values.opsdroid.environment }}
  {{ .name }}: '{{ .value | b64enc }}'
  {{- end }}
{{- end }}