apiVersion: v1
kind: Service
metadata:
  name: opsdroid-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.opsdroid.service.port }}
      targetPort: {{ .Values.opsdroid.service.port }}
      protocol: TCP
  selector:
    app: opsdroid-{{ .Release.Name }}
