{{- if .Values.rasanlu.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: rasanlu-{{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.rasanlu.service.port }}
      targetPort: {{ .Values.rasanlu.service.port }}
      protocol: TCP
  selector:
    app: rasanlu-{{ .Release.Name }}
{{- end -}}
