name: Publish

on:
  push:
    tags: v?[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install chartpress package
        run: |
          pip install --upgrade pip
          pip install --default-timeout=100 git+https://github.com/jupyterhub/chartpress.git
          pip freeze
      - name: install and init helm
        run: |
          sudo apt update -y
          sudo apt install -y curl
          curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sudo bash
          helm init --client-only
      - name: helm lint
        run: helm lint opsdroid
      - name: publish helm chart
        env:
          encrypted_5d28323b2851_key: ${{ secrets.ENCRYPTED_5D28323B2851_KEY }}
          encrypted_5d28323b2851_iv: ${{ secrets.ENCRYPTED_5D28323B2851_IV }}
        if: startsWith(github.ref, 'refs/tags/')
        run: ci/deploy.sh